{% set version = "5.1.16" %}
{% set code_sha256 = "7054de24b90b6d9533329ef8dc89912c5227c83fb447792103279364e13dd452" %}
{% set data_sha256 = "025d4bf904c28cc202f083a67b2ec0ffd68fa2b212a89de327a18cdca8698551" %}


package:
  name: hdfeos5
  version: {{ version }}

source:
  - url: https://git.earthdata.nasa.gov/rest/git-lfs/storage/DAS/hdfeos5/{{ code_sha256 }}?response-content-disposition=attachment%3B%20filename%3D%22HDF-EOS{{ version }}.tar.Z%22%3B%20filename*%3Dutf-8%27%27HDF-EOS{{ version }}.tar.Z
    sha256: {{ code_sha256 }}
    patches:
      # The original remove header patch comes from
      # https://lists.gnu.org/archive/html/guix-devel/2016-09/msg02110.html
      # For more details see the old patch file in the git history.
      - patches/0001-remove-unnecessary-headers.patch
      - patches/0002-fix-automake-files-for-linux-compatibility.patch
  - url: https://git.earthdata.nasa.gov/rest/git-lfs/storage/DAS/hdfeos5/{{ data_sha256 }}?response-content-disposition=attachment%3B%20filename%3D%22HDF-EOS{{ version }}_TESTDRIVERS.tar.Z%22%3B%20filename*%3Dutf-8%27%27HDF-EOS{{ version }}_TESTDRIVERS.tar.Z
    sha256: {{ data_sha256 }}

build:
  number: 10
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - autoconf
    - libtool
    - make
  host:
    - hdf5
    - hdf5-static
    - zlib
  run:
    - hdf5
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libGctp.a  # [not win]
    - test -f ${PREFIX}/lib/libhe5_hdfeos.a  # [not win]

about:
  home: http://hdfeos.org/index.php
  license: Public Domain
  summary: 'Earth Observing System HDF'

extra:
  recipe-maintainers:
    - zklaus
    - ocefpaf
    - jhamman
    - khallock
    - snowman2
    - xylar
