package:
    name: hdfeos5
    version: 5.1.15

source:
    fn: HDF-EOS5.1.15.tar.Z
    url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos5/latest_release/HDF-EOS5.1.15.tar.Z
    md5: 5d607a13dd42e559bfc90e278a8ec919
    patches:
        # http://hdfeos.org/forums/showthread.php?t=673
        - EHapi.c.patch

build:
    number: 3
    skip: True  # [win]

requirements:
    build:
        - hdf5 1.8*
        - zlib 1.2*
    run:
        - hdf5 1.8*
        - zlib 1.2*

test:
    commands:
        - test -f ${PREFIX}/lib/libGctp.a  # [unix]
        - test -f ${PREFIX}/lib/libhe5_hdfeos.a  # [unix]
        - conda inspect linkages -n _test hdfeos5  # [linux]

about:
    home: http://hdfeos.org/index.php
    license: BSD
    summary: Earth Observing System HDF

extra:
    recipe-maintainers:
        - ocefpaf
        - jhamman
