{% set version = "5.1.16" %}

package:
  name: hdfeos5
  version: {{ version }}

source:
  url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos5/latest_release/HDF-EOS{{ version }}.tar.Z
  sha256: 7054de24b90b6d9533329ef8dc89912c5227c83fb447792103279364e13dd452

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - hdf5
    - zlib
  run:
    - hdf5
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libGctp.a  # [not win]
    - test -f ${PREFIX}/lib/libhe5_hdfeos.a  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://hdfeos.org/index.php
  license: Public Domain
  summary: 'Earth Observing System HDF.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
    - khallock
