appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: K1/zOoepN6mTe2T5D2YKHF6mcRKpRQEJ5IrCMJ5CQyLIFbTsd0iHMyT5oriV3Csr4mK/AnQi8mUD+X4vcht/EEiRrLUMXKYZGafv4n4/X+pp8i+sbCjrKki3tMFJKKG0S9JyzTRqtsj2NnBhquVe4yl9ORrnPKShkxbyGAlWtFdOZGKvgiDGTJfCWkjxV4tbSB8ZdbI75wpGtrZ+dOD/aF4/N/PTiSHHRWFkcMZ+olzqGgDxgoKPSg37ar7+kOQe8BpevwOXlZuwy1yVG16A690sRyAaXwf6GTxW3WyBFtlxTivbkjbsveTVP0EtSj+SVPmZsdvvduStYS5au/xPV07mwE4n1JjzbEsoVIMBjWsw1O4GkXQf20JXz8oa7GJIuQ0kbnhGrditRBjdoJnck8Yw+0QrHInyOWS+auYz3gFL5apGhbgnOXtDoK8fQlOfOjz83SKjQQ9Z2hmLOYaw24iqmht+jYNxBkLSfh6brZMWJWSU9vehVT4DpKUPNj6B0S6lus+DXK+zTFgUFYyTENdo07i3XSXoPjn+yXhb94H9GLh49175dNfUX/RVweNSSDs7L5RxSUjQxeMvrOBTPkX/7B2nY+/H5EYtNrqn8l4gNSDqgz/yP8QCfHRA4RTZXAtopXx6wxp8Lv61EPf6lytdo7PF0dIf5fKsVHLn+F4=}
